### PR TITLE
Increase the size proportionally by the number of test limit

### PR DESCRIPTION
**Pull request by charleso**
/cc @Kevin-Lee @thumphries @moodmosaic 

I believe the haskell version is not doing this either. Is it something anyone has been worried about?

### CODE REVIEW

**Comment by moodmosaic** [comment]
I think this looks good as long as we increment by 1 (by default).

The smaller the size is, the faster shrinking will be (theoretically?) Also, if, by default, 100 tests are run, it makes sense to have a size from 0-99. (Or even [0-1 fractional](https://github.com/hedgehogqa/haskell-hedgehog/issues/38#issuecomment-293427345)?)

---

In fact, size [has](https://github.com/nick8325/quickcheck/issues/199) [been](https://github.com/fscheck/FsCheck/issues/87) [confusing](https://github.com/fscheck/FsCheck/issues/268) [overtime](https://github.com/hedgehogqa/haskell-hedgehog/issues/38#issuecomment-409454931) (e.g. some generators totally ignore it) that [I'm wondering if we could remove it entirely using the Range combinators](https://github.com/hedgehogqa/haskell-hedgehog/issues/38#issuecomment-293458877).

In haskell-hedgehog, edge cases of size can be seen in https://github.com/hedgehogqa/haskell-hedgehog/issues/38#issuecomment-409454931.

**Comment by charleso** [comment]
> I think this looks good as long as we increment by 1 (by default).

Not so sure about there being a default so much as it never goes below 1 (ie you have 101+ tests it stops at 1)

**Comment by charleso** [comment]
@moodmosaic I've made another change related to this:

https://github.com/hedgehogqa/scala-hedgehog/pull/57

**Comment by charleso** [comment]
> (Or even 0-1 fractional?)

I did wonder if that would be less confusing. At the moment it's not obvious to the casual observer what size means or is.

**Comment by moodmosaic** [comment]
>At the moment it's not obvious to the casual observer what size means or is.

Right. If only we can have Range take care of it.

**Pull request merged**
