### PR TITLE
Remove higher kind from Gen/Property/Tree

### PR DESCRIPTION
**Pull request by charleso**
@jystic @moodmosaic 

Two main reasons for removing this.

1. It's unlikely that it's actually going to be used by 99.99% of
   users. That is if we had any...

2. To the previous point, removing the kind will hopefully
   increase the chances of not scaring off potential users.

### CODE REVIEW

**Comment by jystic** [comment]
I would like to remove it from Gen/Tree in the Haskell version but I don't think it's possible while retaining the nice monadic `forAll` syntax. We don't have a higher kind in the F# version because we can have side effects.

**Comment by charleso** [comment]
> We don't have a higher kind in the F# version because we can have side effects.

Same with Scala. I didn't mind adding adding it to begin with, but doesn't seem like it's buying me much at this stage. I'm definitely happy to re-add if/when there's enough demand.

**Comment by moodmosaic** [comment]
Sorry, just catching up, back from holidays.

**Comment by moodmosaic** [comment]
>>We don't have a higher kind in the F# version because we can have side effects.
>
>Same with Scala. I didn't mind adding adding it to begin with, but doesn't seem like it's buying me much at this stage. I'm definitely happy to re-add if/when there's enough demand.

:+1:

**Pull request merged**
