### PR TITLE
GitHub Actions - Add Manual builds and sbt cache handling has been simplified

### PR DESCRIPTION
**Pull request by Kevin-Lee**
GitHub Actions - Add Manual builds and sbt cache handling has been simplified

**These manual builds can help me release Hedgehog and retry when it fails.**

### CODE REVIEW

**Comment by charleso** [comment]
@Kevin-Lee not having automated releasing makes me sad. Can we not retry to run it once, and then you can follow up with manual fix-ups? Does it never work on github?

**Comment by Kevin-Lee** [comment]
> @Kevin-Lee not having automated releasing makes me sad. Can we not retry to run it once, and then you can follow up with manual fix-ups? Does it never work on github?

This PR is not about getting rid of the auto-release. It's just like you said, when the auto one failed, we can try the failed one using the manual build in this PR. Otherwise, we have to manually remove all the partially deployed ones from Bintray and try the auto one again which can easily cause the max request limit on Bintray.

**Review by charleso — APPROVED** [review]
Sounds good. Thanks Kevin!

**Comment by Kevin-Lee** [comment]
Oh the only manual one is publishing the doc site. Because it was published before the tagged one was released, the doc site now has some incorrect info. So I think we'd better have the control of when to publish the doc site.

**Pull request merged**
