### PR TITLE
Update to Scala 2.12.11 and 2.13.3

### PR DESCRIPTION
**Pull request by dwestheide**
The previous versions were a bit outdated. While not a problem per se, it does result in a warning when using the Metals extension, because it will drop support for those specific minor versions in a while.

### CODE REVIEW

**Comment by Kevin-Lee** [comment]
Yes, I think `.travis.yml` should be upgraded too. You may have an issue with `kind-projector` once you change them in `.travis.yml` though because of this [Cross compile with the full Scala version](https://github.com/typelevel/kind-projector/issues/15) issue.

As you know, it can be fixed easily by replacing `CrossVersion.binary` with `CrossVersion.full` but doesn't it affect the users if they use Scala versions with no matching kind-projector? I'm not so sure.

**Comment by dwestheide** [comment]
> Yes, I think `.travis.yml` should be upgraded too. You may have an issue with `kind-projector` once you change them in `.travis.yml` though because of this [Cross compile with the full Scala version](https://github.com/typelevel/kind-projector/issues/15) issue.

I updated `travis.yml` as well now. There was no problem with kind-projector, so it seems that kind-projector is binary compatible between Scala 2.13.0 and 2.13.3.

There was, however, a different issue: In Scala 2.13.3, methods with an empty parameter list cannot be invoked any more as if hey had no parameter list. This seems to be in preparation for Scala 3, where doing so will lead to an eta expansion of that method. I had to change a few such method calls in `Framework.scala`, but it wasn't a big deal.

> As you know, it can be fixed easily by replacing `CrossVersion.binary` with `CrossVersion.full` but doesn't it affect the users if they use Scala versions with no matching kind-projector? I'm not so sure.

If I understand correctly, if the hedgehog code still compiles with `CrossVersion.binary` in Travis, there is no problem at all, right? So I think we're good to go with updating to the latest Scala versions.

**Comment by Kevin-Lee** [comment]
> > Yes, I think `.travis.yml` should be upgraded too. You may have an issue with `kind-projector` once you change them in `.travis.yml` though because of this [Cross compile with the full Scala version](https://github.com/typelevel/kind-projector/issues/15) issue.
> 
> I updated `travis.yml` as well now. There was no problem with kind-projector, so it seems that kind-projector is binary compatible between Scala 2.13.0 and 2.13.3.

@dwestheide That's interesting. Oh... I think I know why. It's kind-projector version 0.11.0 which requires full cross version. Sorry I didn't check the version of the kind-projector we used. 😅

> There was, however, a different issue: In Scala 2.13.3, methods with an empty parameter list cannot be invoked any more as if hey had no parameter list. This seems to be in preparation for Scala 3, where doing so will lead to an eta expansion of that method. I had to change a few such method calls in `Framework.scala`, but it wasn't a big deal.

That's good. 👍

> > As you know, it can be fixed easily by replacing `CrossVersion.binary` with `CrossVersion.full` but doesn't it affect the users if they use Scala versions with no matching kind-projector? I'm not so sure.
> 
> If I understand correctly, if the hedgehog code still compiles with `CrossVersion.binary` in Travis, there is no problem at all, right? So I think we're good to go with updating to the latest Scala versions.

Yeah, sorry never mind. 🙂

Thanks for the PR. I think Charles should have a look at every PR but this one seems obvious and good to go.

**Comment by Kevin-Lee** [comment]
and thanks @Philippus for the review!

**Pull request merged**
