### PR TITLE
Configure Dependabot

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@Kevin-Lee please review

**Comment by Kevin-Lee** [comment]
@gliptak I'm sorry Gábor but I don't really understand this PR. As far as I know, dependabot doesn't support Scala and sbt. Does it now?

**Comment by gliptak** [comment]
Yes, no Scala support. I does work `Github Actions` though

**Comment by Kevin-Lee** [comment]
Oh so it's for GitHub Actions not for the project, isn't it?

**Comment by Kevin-Lee** [comment]
OK, got it now. Thanks!
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

**Review by Kevin-Lee — APPROVED** [review]

**Pull request merged**
