### PR TITLE
Hedgehog Website

### PR DESCRIPTION
**Pull request by Kevin-Lee**
## Hedgehog Website
* The site has benn built with Docusaurus 2
* Mdoc is used for potential code compile and run for the docs
* sbt-docusaur is used to publish the site to GitHub Pages
* GitHub Actions has been set to build and publish the doc site
* The docs in Markdown files have been moved to the new location.
* Add: the latest tagged version to the getting-started.md
* Add: Supported Scala version info
* Add: Search bar

I've published it to mine to show what it looks like.
https://kevin-lee.github.io/scala-hedgehog

### CODE REVIEW

**Comment by charleso** [comment]
@Kevin-Lee To update the CNAME you need to speak to Jacob. Before you do I wouldn't mind knowing what others in the hedgehog community think about this. I'm still not sure if it's a good idea to have a separate doc site for scala, but it definitely shouldn't be up to me. :) Looks great though!!!

**Comment by Kevin-Lee** [comment]
@charleso Sure, thanks. I've just asked it in the Slack channel. 🙂

**Comment by charleso** [comment]
@Kevin-Lee If other people are happy I'm happy. Totally your call, if you want to campion it then don't let me stand in your way. :) 👍

**Comment by Kevin-Lee** [comment]
@charleso Thanks Charles. I think it's good to have one per each language and I'm happy to help or do it for other languages as well.
I still need Jacob's help to have a proper site URL like `hedgehog.qa/docs/scala` which is suggested by Nikos on Hedgehog Slack channel. I also think it's better than having `scala.hedgehog.qa`.

**Comment by Kevin-Lee** [comment]
@charleso I haven't got any answer from Jacob yet. I guess he's busy, 
I'd like to merge this PR. I'll introduce Hedgehog to my colleagues and it would be good for me to convince them to use it with a proper website..

**Comment by charleso** [comment]
> I'd like to merge this PR. 

Go for it. You're doing the real maintenance on hedgehog these days. :)

**Comment by Kevin-Lee** [comment]
@charleso Thank you! 🙂

**Pull request merged**
